name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: 1.18

      - run: make
